In [2]:
import pandas as pd

In [67]:
items = pd.read_csv('database/datasource/items.csv')

In [68]:
items

,ItemID,Inactive,Item,Variety,Color,ShouldStock,TypeID,LabelDescription,Definition,PictureLayout,PictureLink,SunConditions
0,8740,False,Nicotiana mutabalis,Select Misty Dawn,Mix,False,6.0,Ht. 4-5' Well branched and full of rosey pink ...,NaN,NaN,NaN,all.jpg
1,8741,False,Tomato,Chilli Verde,NaN,False,8.0,"Pepper shaped fruits, with very few seeds, rip...",NaN,NaN,NaN,sun.jpg
2,8742,False,Browalia americana,Blue Lady,NaN,False,6.0,Ht. 2' This little gem blooms all season long ...,NaN,NaN,NaN,all_conditions.jpg
3,8743,False,Browalia americana,Sky Blue,NaN,False,6.0,"Ht. 18"" Plant in fertile soil, it will produce...",NaN,NaN,NaN,all_conditions.jpg
4,8744,False,Nicotiana,Select Watercolors,NaN,False,6.0,"Ht. 3-4' A mix of muted shades of green, pink,...",NaN,NaN,NaN,all_conditions.jpg
...,...,...,...,...,...,...,...,...,...,...,...,...
7249,8312,False,Pansy,Matrix True Blue,NaN,False,6.0,"Matrix is designed for cool-season, short-day ...",NaN,NaN,NaN,blank.jpg
7250,8313,False,Pansy,Magestic Giants II Blue Jeans Blotch,NaN,False,6.0,NaN,NaN,NaN,NaN,blank.jpg
7251,8314,False,Pansy,Delta Wine & Cheese,Mix,False,6.0,NaN,NaN,NaN,NaN,blank.jpg
7252,8315,False,Pansy,Delta Premium Persian Medly,Mix,False,6.0,NaN,NaN,NaN,NaN,blank.jpg
7253,8316,NaN,Begonia,I'Conia Bacio Peach,Peach,False,6.0,Medium to large blooms against dark foliage. S...,NaN,NaN,NaN,part-sun_shade.jpg

In [69]:
items['ShouldStock'].dtype, items['Inactive'].dtype

(dtype('bool'), dtype('O'))

In [70]:
items['ShouldStock'] = items['ShouldStock'].astype(bool)
items['Inactive'] = items['Inactive'].astype(bool)

print(items['ShouldStock'].dtype, items['Inactive'].dtype)
items.head()

bool bool

,ItemID,Inactive,Item,Variety,Color,ShouldStock,TypeID,LabelDescription,Definition,PictureLayout,PictureLink,SunConditions
0,8740,False,Nicotiana mutabalis,Select Misty Dawn,Mix,False,6.0,Ht. 4-5' Well branched and full of rosey pink ...,NaN,NaN,NaN,all.jpg
1,8741,False,Tomato,Chilli Verde,NaN,False,8.0,"Pepper shaped fruits, with very few seeds, rip...",NaN,NaN,NaN,sun.jpg
2,8742,False,Browalia americana,Blue Lady,NaN,False,6.0,Ht. 2' This little gem blooms all season long ...,NaN,NaN,NaN,all_conditions.jpg
3,8743,False,Browalia americana,Sky Blue,NaN,False,6.0,"Ht. 18"" Plant in fertile soil, it will produce...",NaN,NaN,NaN,all_conditions.jpg
4,8744,False,Nicotiana,Select Watercolors,NaN,False,6.0,"Ht. 3-4' A mix of muted shades of green, pink,...",NaN,NaN,NaN,all_conditions.jpg

AttributeError: 'float' object has no attribute 'dtype'

In [81]:
items_clean_df = items.copy()

# Remove problematic characters from text columns
text_columns = ['Inactive', 'Item', 'Variety', 'Color', 'LabelDescription', 'Definition', 'PictureLayout', 'PictureLink', 'SunConditions']

for col in text_columns:
    if col in items_clean_df.columns:
        items_clean_df[col] = items_clean_df[col].astype(str).str.encode('ascii', errors='ignore').str.decode('ascii')

# Save cleaned CSV
items_clean_df.to_csv('database/datasource/items_cleaned.csv', index=False, encoding='utf-8')

In [38]:
items.iloc[0]['LabelDescription']

"Ht. 4-5' Well branched and full of rosey pink and blush white flowers. A hummingbird favorite. Fragrant."

In [39]:
items_clean = pd.read_csv('datasource/items_cleaned.csv')

items_clean.head()

,ItemID,Inactive,Item,Variety,Color,ShouldStock,TypeID,LabelDescription,Definition,PictureLayout,PictureLink,SunConditions
0,8740,False,Nicotiana mutabalis,Select Misty Dawn,Mix,False,6.0,Ht. 4-5' Well branched and full of rosey pink ...,NaN,NaN,NaN,all.jpg
1,8741,False,Tomato,Chilli Verde,NaN,False,8.0,"Pepper shaped fruits, with very few seeds, rip...",NaN,NaN,NaN,sun.jpg
2,8742,False,Browalia americana,Blue Lady,NaN,False,6.0,Ht. 2' This little gem blooms all season long ...,NaN,NaN,NaN,all_conditions.jpg
3,8743,False,Browalia americana,Sky Blue,NaN,False,6.0,"Ht. 18"" Plant in fertile soil, it will produce...",NaN,NaN,NaN,all_conditions.jpg
4,8744,False,Nicotiana,Select Watercolors,NaN,False,6.0,"Ht. 3-4' A mix of muted shades of green, pink,...",NaN,NaN,NaN,all_conditions.jpg

In [40]:
items_clean['ShouldStock'].unique()

array([False,  True])

In [55]:
inactive_map = {}

ShouldStockMap = {
    'False': 0,
    'True': 1,
    False: 0,
    True: 1,
    'true': 1,
    'false': 0,
}

InactiveMap= {
   'False': 0,
    'True': 1,
    False: 0,
    True: 1,
    'true': 1,
    'false': 0, 
}


items_clean['ShouldStock'] = items_clean['ShouldStock'].map(ShouldStockMap)
items_clean['Inactive'] = items_clean['Inactive'].map(InactiveMap)
items_clean['ShouldStock'].notnull().astype(int)
items_clean['Inactive'].notnull().astype(int)
items_clean.head()

,ItemID,Inactive,Item,Variety,Color,ShouldStock,TypeID,LabelDescription,Definition,PictureLayout,PictureLink,SunConditions
0,8740,0.0,Nicotiana mutabalis,Select Misty Dawn,Mix,0,6.0,Ht. 4-5' Well branched and full of rosey pink ...,NaN,NaN,NaN,all.jpg
1,8741,0.0,Tomato,Chilli Verde,NaN,0,8.0,"Pepper shaped fruits, with very few seeds, rip...",NaN,NaN,NaN,sun.jpg
2,8742,0.0,Browalia americana,Blue Lady,NaN,0,6.0,Ht. 2' This little gem blooms all season long ...,NaN,NaN,NaN,all_conditions.jpg
3,8743,0.0,Browalia americana,Sky Blue,NaN,0,6.0,"Ht. 18"" Plant in fertile soil, it will produce...",NaN,NaN,NaN,all_conditions.jpg
4,8744,0.0,Nicotiana,Select Watercolors,NaN,0,6.0,"Ht. 3-4' A mix of muted shades of green, pink,...",NaN,NaN,NaN,all_conditions.jpg

In [60]:
print(items_clean['ShouldStock'].unique(), items_clean['Inactive'].unique())

[0 1] [ 0. nan  1.]

In [46]:
items_clean

,ItemID,Inactive,Item,Variety,Color,ShouldStock,TypeID,LabelDescription,Definition,PictureLayout,PictureLink,SunConditions
0,8740,0.0,Nicotiana mutabalis,Select Misty Dawn,Mix,0,6.0,Ht. 4-5' Well branched and full of rosey pink ...,NaN,NaN,NaN,all.jpg
1,8741,0.0,Tomato,Chilli Verde,NaN,0,8.0,"Pepper shaped fruits, with very few seeds, rip...",NaN,NaN,NaN,sun.jpg
2,8742,0.0,Browalia americana,Blue Lady,NaN,0,6.0,Ht. 2' This little gem blooms all season long ...,NaN,NaN,NaN,all_conditions.jpg
3,8743,0.0,Browalia americana,Sky Blue,NaN,0,6.0,"Ht. 18"" Plant in fertile soil, it will produce...",NaN,NaN,NaN,all_conditions.jpg
4,8744,0.0,Nicotiana,Select Watercolors,NaN,0,6.0,"Ht. 3-4' A mix of muted shades of green, pink,...",NaN,NaN,NaN,all_conditions.jpg
...,...,...,...,...,...,...,...,...,...,...,...,...
7249,8312,0.0,Pansy,Matrix True Blue,NaN,0,6.0,"Matrix is designed for cool-season, short-day ...",NaN,NaN,NaN,blank.jpg
7250,8313,0.0,Pansy,Magestic Giants II Blue Jeans Blotch,NaN,0,6.0,NaN,NaN,NaN,NaN,blank.jpg
7251,8314,0.0,Pansy,Delta Wine & Cheese,Mix,0,6.0,NaN,NaN,NaN,NaN,blank.jpg
7252,8315,0.0,Pansy,Delta Premium Persian Medly,Mix,0,6.0,NaN,NaN,NaN,NaN,blank.jpg
7253,8316,NaN,Begonia,I'Conia Bacio Peach,Peach,0,6.0,Medium to large blooms against dark foliage. S...,NaN,NaN,NaN,part-sun_shade.jpg

In [47]:
items_clean.to_csv('datasource/items_cleaned.csv', index=False)

In [ ]:
import pandas as pd

# Read the CSV with error handling
df = pd.read_csv('datasource/items.csv', encoding='utf-8')
# or try:
# df = pd.read_csv('your_file.csv', encoding='latin1')

# Clean the data and save a new CSV
df_clean = df.copy()

# Remove problematic characters from text columns
text_columns = ['Inactive', 'Item', 'Variety', 'Color', 'LabelDescription', 'Definition', 'PictureLayout', 'PictureLink', 'SunConditions']

for col in text_columns:
    if col in df_clean.columns:
        df_clean[col] = df_clean[col].astype(str).str.encode('ascii', errors='ignore').str.decode('ascii')

# Save cleaned CSV
df_clean.to_csv('datasource/items_cleaned.csv', index=False, encoding='utf-8')

In [80]:
import pandas as pd

# Read the CSV with error handling
df = pd.read_csv('datasource/items.csv', encoding='utf-8')
# or try:
# df = pd.read_csv('your_file.csv', encoding='latin1')

# Clean the data and save a new CSV
df_clean = df.copy()

# Remove problematic characters from text columns
text_columns = ['Inactive', 'Item', 'Variety', 'Color', 'LabelDescription', 'Definition', 'PictureLayout', 'PictureLink', 'SunConditions']

for col in text_columns:
    if col in df_clean.columns:
        df_clean[col] = df_clean[col].astype(str).str.encode('ascii', errors='ignore').str.decode('ascii')

# Save cleaned CSV
df_clean.to_csv('datasource/items_cleaned.csv', index=False, encoding='utf-8')

FileNotFoundError: [Errno 2] No such file or directory: 'datasource/items.csv'

In [ ]:
import pandas as pd

# Read the CSV with error handling
df = pd.read_csv('datasource/items.csv', encoding='utf-8')
# or try:
# df = pd.read_csv('your_file.csv', encoding='latin1')

# Clean the data and save a new CSV
df_clean = df.copy()

# Remove problematic characters from text columns
text_columns = ['Inactive', 'Item', 'Variety', 'Color', 'LabelDescription', 'Definition', 'PictureLayout', 'PictureLink', 'SunConditions']

for col in text_columns:
    if col in df_clean.columns:
        df_clean[col] = df_clean[col].astype(str).str.encode('ascii', errors='ignore').str.decode('ascii')

# Save cleaned CSV
df_clean.to_csv('datasource/items_cleaned.csv', index=False, encoding='utf-8')

In [ ]:
import pandas as pd

# Read the CSV with error handling
df = pd.read_csv('datasource/items.csv', encoding='utf-8')
# or try:
# df = pd.read_csv('your_file.csv', encoding='latin1')

# Clean the data and save a new CSV
df_clean = df.copy()

# Remove problematic characters from text columns
text_columns = ['Inactive', 'Item', 'Variety', 'Color', 'LabelDescription', 'Definition', 'PictureLayout', 'PictureLink', 'SunConditions']

for col in text_columns:
    if col in df_clean.columns:
        df_clean[col] = df_clean[col].astype(str).str.encode('ascii', errors='ignore').str.decode('ascii')

# Save cleaned CSV
df_clean.to_csv('datasource/items_cleaned.csv', index=False, encoding='utf-8')

In [50]:
# Create mapping for TypeID = 0 items
type_mapping = {
    'Mum': 7,                    # Perennial
    'Thunbergia': 6,            # Annual
    'Clematis': 7,              # Perennial
    'Ple': 7,                   # Assuming perennial
    'Hosta': 7,                 # Perennial
    'Pumpkin': 8,               # Vegetable
    'Salvia': 6,                # Annual (most common type)
    'Cucumber-Pickle': 8,        # Vegetable
    'Aster': 7,                 # Perennial
    'Geranium': 6,              # Annual
    'Begonia': 6,               # Annual
    'Disporum': 7,              # Perennial
    'Mesculn-Pak choi': 8,      # Vegetable
    'Campanula': 7              # Perennial
}

# Apply the mapping
for item_name, new_type_id in type_mapping.items():
    items_clean.loc[(items_clean['TypeID'] == 0) & (items_clean['Item'] == item_name), 'TypeID'] = new_type_id

# Check if any TypeID = 0 items remain
remaining = items_clean[items_clean['TypeID'] == 0]['Item'].unique()
if len(remaining) > 0:
    print(f"Items still with TypeID = 0: {remaining}")

items_clean

Items still with TypeID = 0: [nan]

,ItemID,Inactive,Item,Variety,Color,ShouldStock,TypeID,LabelDescription,Definition,PictureLayout,PictureLink,SunConditions
0,8740,0.0,Nicotiana mutabalis,Select Misty Dawn,Mix,0,6.0,Ht. 4-5' Well branched and full of rosey pink ...,NaN,NaN,NaN,all.jpg
1,8741,0.0,Tomato,Chilli Verde,NaN,0,8.0,"Pepper shaped fruits, with very few seeds, rip...",NaN,NaN,NaN,sun.jpg
2,8742,0.0,Browalia americana,Blue Lady,NaN,0,6.0,Ht. 2' This little gem blooms all season long ...,NaN,NaN,NaN,all_conditions.jpg
3,8743,0.0,Browalia americana,Sky Blue,NaN,0,6.0,"Ht. 18"" Plant in fertile soil, it will produce...",NaN,NaN,NaN,all_conditions.jpg
4,8744,0.0,Nicotiana,Select Watercolors,NaN,0,6.0,"Ht. 3-4' A mix of muted shades of green, pink,...",NaN,NaN,NaN,all_conditions.jpg
...,...,...,...,...,...,...,...,...,...,...,...,...
7249,8312,0.0,Pansy,Matrix True Blue,NaN,0,6.0,"Matrix is designed for cool-season, short-day ...",NaN,NaN,NaN,blank.jpg
7250,8313,0.0,Pansy,Magestic Giants II Blue Jeans Blotch,NaN,0,6.0,NaN,NaN,NaN,NaN,blank.jpg
7251,8314,0.0,Pansy,Delta Wine & Cheese,Mix,0,6.0,NaN,NaN,NaN,NaN,blank.jpg
7252,8315,0.0,Pansy,Delta Premium Persian Medly,Mix,0,6.0,NaN,NaN,NaN,NaN,blank.jpg
7253,8316,NaN,Begonia,I'Conia Bacio Peach,Peach,0,6.0,Medium to large blooms against dark foliage. S...,NaN,NaN,NaN,part-sun_shade.jpg

In [52]:
items_clean.to_csv('items_categorized.csv', index=False)
print("Categorization complete!")

Categorization complete!

In [53]:
valid_type_ids = [3, 4, 6, 7, 8, 11, 12, 13]

print("Invalid TypeIDs found:", items_clean[~items_clean['TypeID'].isin(valid_type_ids)]['TypeID'].unique())

# Map any invalid TypeIDs to a default (like 7 for Perennial)
items_clean.loc[~items_clean['TypeID'].isin(valid_type_ids), 'TypeID'] = 7

print("After fixing - TypeID counts:")
print(items_clean['TypeID'].value_counts().sort_index())

items_clean.to_csv('forced_valid_typeids.csv', index=False)

Invalid TypeIDs found: [ 0. nan]
After fixing - TypeID counts:
TypeID
3.0        2
6.0     3918
7.0     2187
8.0     1047
11.0      65
12.0      29
13.0       6
Name: count, dtype: int64